vim.lsp.enable 'lua_ls'
vim.lsp.enable 'basedpyright'
vim.lsp.enable 'bashls'
vim.lsp.enable 'postgres_lsp'
vim.lsp.enable 'cssls'
vim.lsp.enable 'html'
vim.lsp.enable 'docker_compose_language_service'
