# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'
set -g @plugin 'erikw/tmux-powerline'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'


# split mouse
set -g mouse on


# set-option -g window-status-format ""
# set-option -g window-status-current-format ""

# Display color
# set -g default-terminal "screen-256color"
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",*256col*:Tc"

# set-option -g default-command "exec zsh -l"
# set-option -g update-environment "PWD"

# 使用当前窗格的目录作为新窗格初始目录
# bind '"' split-window -v -c "#{pane_current_path}"
# bind % split-window -h -c "#{pane_current_path}"

# 新窗口继承当前窗格路径
bind c new-window -c "#{pane_current_path}"
