return {
  'nvim-treesitter/nvim-treesitter',
  event = 'VeryLazy',
  build = ':TSUpdate',
  main = 'nvim-treesitter.configs',
  opts = {
    ensure_installed = {
      'bash',
      'c',
      'csv',
      'diff',
      'dockerfile',
      'go',
      'git_config',
      'git_rebase',
      'gitcommit',
      'gitignore',
      'html',
      'jinja',
      'jinja_inline',
      'json',
      'jsonc',
      'lua',
      'luadoc',
      'markdown',
      'markdown_inline',
      'nginx',
      'python',
      'powershell',
      'query',
      'sql',
      'ssh_config',
      'toml',
      'vim',
      'vimdoc',
      'yaml',
    },
    auto_install = true,
    highlight = { enable = true },
  },
}
